config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions do
    resources :comments
  end
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :option_a
  validates_presence_of :option_b
  has_many :comments
  has_attached_file :image_a, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image_a, :content_type => /\Aimage\/.*\Z/
  has_attached_file :image_b, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image_b, :content_type => /\Aimage\/.*\Z/
  after_save :update_vote_count

  def recent_comments(n)
    comments.order(id: :desc).limit(n)
  end

  def option_a_percentage
    "#{100*option_a_count/vote_count}%"
  end

  def option_b_percentage
    "#{100*option_b_count/vote_count}%"
  end

  private
  def update_vote_count
    update_column(:vote_count, option_a_count + option_b_count)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index

  end

  def create
    @question = Question.find(params[:question_id])
    @comment = Comment.create(comment_params)
    @question.comments << @comment
    if current_user
      current_user.comments << @comment
    else
      anon = User.find_by email: 'anon@anon.who'
      anon.comments << @comment
    end
    respond_to do |format|
      format.html
      format.js
    end
  end


  private
  def comment_params
    params.require(:comment).permit(:text)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :update]

  def index
    sleep 1
    @questions = Question.order(sort_options).paginate(page: params[:page], per_page: 5)
    flash[:notice] = ''
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @question = Question.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @question = Question.create(question_params)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
    respond_to do |format|
      format.js
    end
  end

private

  def question_params
    params.require(:question).permit :option_a, :option_b, :option_a_count, :option_b_count, :image_a, :image_b
  end

  def sort_options
    if params[:sort]
      params[:sort]
    else
      "id desc"
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    flash[:notice] = 'You would rather sign in :)'
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<%= comment.user.email %> says <%= comment.text %>

app/views/comments/_comments.html.erb
<div id="comments_<%= question.id %>">
  <h5>Comments</h5>
  <ul class="list-unstyled">
    <% question.recent_comments(3).each do |comment| %>
      <li><%= render "comment", comment: comment %></li>
      <hr>
    <% end %>
  </ul>
</div>

app/views/comments/_form.html.erb
<%= form_for [question, Comment.new], :html => { id: "new_comment_#{question.id}" }, remote: true do |f| %>
  <div class="form-group">
    <%= f.text_field :text, placeholder: "Write a comment", class: "form-control" %>
  </div>
  <%= f.submit "Comment", class: "btn btn-primary form-control" %>
<% end %>

app/views/comments/create.js.erb
$("#new_comment_<%= @question.id %>").replaceWith("<%= j render('comments', question: @question) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Preferer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: "navbar-brand"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav special-color">
        <% if user_signed_in? %>
          <!-- remote: true allows AJAX -->
          <li><%= link_to 'Ask a Question', new_question_path, remote: true %></li>
        <% else %>
          <li><%= link_to 'Ask a Question', new_user_session_path %></li>
        <% end %>
        <li><%= link_to 'Questions', questions_path %></li>
      </ul>

      <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
          <p class="navbar-text">Signed in as <%= current_user.email %></p>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>

        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Create Account", new_user_registration_path %></li>
        <% end %>
      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <div class="form-group">
    <%= f.label :option_a, "Option A" %>
    <%= f.text_field :option_a, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_a, "Image A" %>
    <%= f.file_field :image_a, autocomplete: "off" %>
  </div>

  <div class="form-group">
    <%= f.label :option_b, "Option B" %>
    <%= f.text_field :option_b, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :image_b, "Image B" %>
    <%= f.file_field :image_b, autocomplete: "off" %>
  </div>

  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/questions/_question.html.erb
<div id="<%=question.id %>" class="row">
  <div class="col-md-8">
    <h3>
      Would you rather:
    </h3>
    <div class="row">
      <div class="col-md-5">
        <div class="question-choice">
          <div id="question_<%=question.id%>_option_a_link_container">
            <%= link_to question_path(question, question: { option_a_count: question.option_a_count + 1}),
                                id: "question_#{question.id}_option_a_link", method: :patch, remote: true do %>
              <%= image_tag question.image_a.url(:medium), class: "image" %>
            <% end %>
          </div>
          <h4 id="question_<%=question.id%>_option_a" class="text-center">
            <%= question.option_a %>
          </h4>
        </div>
      </div>
      <div class="col-md-2">
        <h4 id="question_<%=question.id%>_votes" class="text-center">
          or
        </h4>
      </div>
      <div class="col-md-5">
        <div class="question-choice">
          <div id="question_<%=question.id%>_option_b_link_container">
            <%= link_to question_path(question, question: { option_b_count: question.option_b_count + 1}),
                              id: "question_#{question.id}_option_b_link", method: :patch, remote: true do %>
              <%= image_tag question.image_b.url(:medium), class: "image" %>
            <% end %>
          </div>
          <h4 id="question_<%=question.id%>_option_b" class="text-center">
            <%= question.option_b %>
          </h4>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <%= render "comments/form", question: question %>
  </div>
</div>
<hr>

app/views/questions/_questions.html.erb
<h3><%= link_to 'Sort by votes', :sort => "vote_count desc" %></h3>

<ul class="list-unstyled">
  <% @questions.each do |question| %>
    <li class="question">
      <%= render "question", question: question %>
    </li>
  <% end %>
</ul>

app/views/questions/create.js.erb
$('#new_question').remove();
$('#new_question_link').show();
$('#questions').append('<%= j render(@question, question: @question) %>');

app/views/questions/index.html.erb
<div id="top-of-page">

</div>
<hr>
<div id="questions">
  <%= render "questions" %>
</div>


<%= will_paginate @questions %>

app/views/questions/index.js.erb
$('#questions').append('<%= j render("questions") %>');
$('.pagination').replaceWith('<%= j will_paginate(@questions) %>');
$("#loading").remove();

$(window).scroll(function() {
  var url = $('.pagination .next_page').attr('href');
  if (url && $(window).scrollTop() > $(document).height() - $(window).height() - 50) {
    $(window).off("scroll");
    $("#questions").append("<p id='loading'>Loading more questions...</p>");
    $.getScript(url);
  }
});

$('.pagination').hide();

app/views/questions/new.js.erb
$("#top-of-page").empty().append('<%= j render("form") %>')

app/views/questions/update.js.erb
$("#question_<%= @question.id %>_option_a").html("<%= @question.option_a_percentage %>");
$("#question_<%= @question.id %>_option_b").html("<%= @question.option_b_percentage %>");
$("#question_<%= @question.id %>_votes").html("<%= @question.vote_count %> votes");
$("#question_<%= @question.id %>_option_a_link_container").html("<%= j image_tag @question.image_a.url(:medium), class: 'image' %>");
$("#question_<%= @question.id %>_option_b_link_container").html("<%= j image_tag @question.image_b.url(:medium), class: 'image' %>");

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>